### ISSUE TITLE
Linking items to chat

### ISSUE THREAD

**Issue by olepg** [SwimmingTiger/ClassicCodex#10]
Hi

It's currently not possible to link items from classic codex to chat.
There is a work around, where one can link to a battle.net friend and then use that link in normal chat.

**Comment by SwimmingTiger** [comment]
The format of the link needs to be modified. I will try to fix it.

**Comment by SwimmingTiger** [comment]
Fixed at https://github.com/SwimmingTiger/ClassicCodex/commit/307b2ec5eb1d99b9f99fe7b6866c08127450c106

https://github.com/SwimmingTiger/ClassicCodex/releases/tag/v1.3.5
