### ISSUE TITLE
Quest: Mudrock soup and bugs (Alliance)

### ISSUE THREAD

**Issue by Meridaw** [SwimmingTiger/ClassicCodex#11]
Mudrock tortoise level 36-37 also drop the quest item Forked mudrock tongue.

**Comment by SwimmingTiger** [comment]
Recorded, will be corrected. Thank you.

**Comment by SwimmingTiger** [comment]
The drop has been recorded in the database, but the coordinates of `Mudrock Tortoise` are missing. So it is not displayed on the map.

I consider introducing coordinate information from Questie.

**Comment by Meridaw** [comment]
The cords are also displayed on wowhead if you hover over the dots on the "This NPC can be found" picture.

**Comment by SwimmingTiger** [comment]
v1.3.7 should fix this.
