### ISSUE TITLE
New Feature - Option to load addon data on demand

### ISSUE THREAD

**Issue by rdstern90** [SwimmingTiger/ClassicCodex#17]
I noticed that ClassicCodex makes up 68% or 137.5 Mb of my addon ram usage out of 54 addons. Even TradeSkillMaster (the 2nd biggest addon I have) only uses 21 Mb. This is to be expected as its such an amazing and large scale searchable database of all the data in the game, but perhaps we could have an option to load it on demand after the game's load screen has already passed. The majority of large dataset type addons tend to do this now (atlasloot, dbm, gathermate2, etc). I have found myself having to keep ClassicCodex disabled on the characters I raid with because it has definitely caused me to miss world buffs before. I would prefer to have the game freeze for 5 seconds the first time I open ClassicCodex each day than have it add 5 seconds to load into my characters and possibly miss a world buff.

**Comment by SwimmingTiger** [comment]
ClassicCodex has been changed to on-demand loading since May 23, 2021. Other localization data different from the current game language will not be loaded to reduce the memory usage.
