### ISSUE TITLE
ClassicCodex-v1.4.2-bc folder structure is wrong?

### ISSUE THREAD

**Issue by ghost** [SwimmingTiger/ClassicCodex#23]
Here is folder structure for v1.4.1 BC:
![ClassicCodex141folder](https://user-images.githubusercontent.com/21213705/119265388-2fe44900-bbef-11eb-86b8-fbb65e918401.jpg)

And here is one for v1.4.2 BC:
![ClassicCodex142folder](https://user-images.githubusercontent.com/21213705/119265397-3a064780-bbef-11eb-9076-b2d3f9225235.jpg)

Is this intended, or is much stuff missing?

Edit: Noticed .toc files, and how they been changed dramatically, so this might be intended after all?

**Comment by SwimmingTiger** [comment]
This directory contains multiple addons, just like the release of DBM or NeatPlates. These addons should be placed in the AddOns folder at the same time.

The reason for this is: adding TBC data significantly increases the loading time, even on the SSD, the time required to load all language files at the same time becomes unbearable. So I can only split different languages into different plug-ins, and then use on-demand loading to load only the languages used by the client.

This significantly reduces the load time, and the load time is back to the state before adding TBC, even faster.
