### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by huzhuoliang** [SwimmingTiger/ClassicCodex#24]
简中版本，【讨厌的蝙蝠】任务在小地图和大地图上翻译错误，应该是【毒性瘟疫蝙蝠】和【巨型瘟疫蝙蝠】，而翻译是【毒性天灾蝙蝠】和【巨型天灾蝙蝠】
![WoWScrnShot_052521_015710](https://user-images.githubusercontent.com/26997744/119388289-aa4ebf00-bcfc-11eb-9019-9ba7448460b2.jpg)

**Comment by huzhuoliang** [comment]
我发现在units.lua和units-tbc.lua里的翻译不同，现在用的是units-tbc.lua。tcb更新后官方会有翻译的变更吗？如果有这个问题可能忍两天就过去了。

**Comment by SwimmingTiger** [comment]
翻译数据来自[pfQuest](https://shagu.org/pfQuest/)，它是一个为真正的60年代和TBC时代客户端开发的任务插件，所以里面的翻译也是那个时代的翻译，现在可能改了。
至于TBC和60年代数据集里的翻译为什么不一样，我也不知道，这属于软件考古问题了。
不过，现在应该可以从Wowhead把TBC怀旧服的全部翻译拉取一遍进行更新。我会尝试进行。

**Comment by EKE00372** [comment]
pfQuest的資料来自芒果單機而不是官方的經典版，所以有差異；另外Questie已經有完整正確的TBC版本zhCN/zhTW全數據，可以直接從它導入，這是我們在beta時期抓取的數據，比wowhead還全一點，尤其是zhTW
