### ISSUE TITLE
Quest #0 missing

### ISSUE THREAD

**Issue by ghost** [SwimmingTiger/ClassicCodex#25]
Using v1.4.3, was on Redridge Mountains as Draenei mage (lvl 20)

Got this error: 
[ClassicCodex] Quest #0 missing

Not sure does this help much at all, as there are no other logs included.

And it does seems like it does it only once, not anymore again after relogin or such.

**Comment by SwimmingTiger** [comment]
I also observed the error. It looks like I should create a patch for this.
