### ISSUE TITLE
Feature Request:  Interface with TomTom

### ISSUE THREAD

**Issue by rbpaiett** [SwimmingTiger/ClassicCodex#4]
Humbly requesting that a feature be added where if you have a mark/icon on the map that says something like:

Greater Plainstrider

Please make it so a player can do something like <Ctrl><Right Click> and a crazy taxi arrow will appear with the title 'Greater Plainstrider'.  Example addon:  Questie.

Right now, the icon even blocks anyone from putting a TomTom waypoint on top of it.

**Comment by SwimmingTiger** [comment]
This feature will be considered.
I need to learn how to use TomTom with Questie first. 😂

**Comment by rbpaiett** [comment]
I appreciate you even taking a look at it.  The previous dev was less than enthused about doing it.  The guy over at TomTom told me he'll be glad to provide any info.

**Comment by SwimmingTiger** [comment]
Done in https://github.com/SwimmingTiger/ClassicCodex/releases/tag/v1.3.6
# New in v1.3.6
* Added TomTom integration. Hold down Ctrl and click on a marker to add a TomTom arrow.
