### ISSUE TITLE
1.3.2 favorite add

### ISSUE THREAD

**Issue by Road-block** [SwimmingTiger/ClassicCodex#9]
```
2x ClassicCodex\browser.lua:231: attempt to index field '?' (a nil value)
ClassicCodex\browser.lua:231: in function <ClassicCodex\browser.lua:219>
```

When trying to add a favorite from search result (objects tab)

**Comment by SwimmingTiger** [comment]
It caused by a typo here:
https://github.com/SwimmingTiger/ClassicCodex/blob/37df5053cad0aca44024f6d3787ec746cae71694/browser.lua#L3

`objets` should be `objects`...

**Comment by SwimmingTiger** [comment]
fixed
